os: linux
language: cpp
compiler: gcc
sudo: false

branches:
   only:
     - master
     - develop

before_install:
   - if [ "$CXX" = "g++" ]; then export CXX="g++-6"; fi
   - wget https://github.com/google/googletest/archive/master.zip -O /tmp/gtest.zip
   - unzip /tmp/gtest.zip
   - cd googletest-master
   - cmake .
   - make
   - sudo cp -a googletest/include/gtest /usr/include
   - sudo cp -a lib/libgtest_main.a lib/libgtest.a /usr/lib/
   - cd "${TRAVIS_BUILD_DIR}"

addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       - g++-6
       - libglu1-mesa-dev
       - freeglut3-dev
       - mesa-common-dev

before_script:
   - git clone https://github.com/simonfuhrmann/mve ../mve

script:
    - make -C ../mve
    - make
    - make test
    - ./tests/test
